### ISSUE TITLE
Add Spring Boot Actuator to API Gateway - is completely irrelevant!

### ISSUE THREAD

**Issue by hazartilirot** [simplyi/SpringCloudVideoCourse#10]
Wow, I just don't understand the purpose of two Gateway API like Zuul and spring boot gateway api. Anyway, the code is completely different from what I have and there is no explanation.

**Comment by simplyi** [comment]
There is no explanation here in Git pages. These projects are part of a
video course. Explanation of why there two API gateways and how to create
these projects is in a video course.

**Comment by hazartilirot** [comment]
I know Sergey. I am glad from hearing you.
I am watching the course. That is exactly the reason why I am writing. In the course you split some lessons explaining how to set parameters for Zuul Gateway and Spring Cloud Gateway API, but then when I reached "Add Spring Boot Actuator to API Gateway" and there is only for Zuul. 

Sorry for disturbance, now I see you have updated the course: **[Updated] Add Spring Boot Actuator to Spring Cloud Gateway**

Sorry for bothering you. This one was really unnecessary.

**Comment by simplyi** [comment]
Yes, I am currently updating video lessons in this course. It is
challenging to update video lessons that we recorded in a step-by-step
manner. Many lessons are dependent on each other. This means that to make
one little change in code I need to update dozens of video lessons. Which
is hard. And if there is another change in code, I need to rework another
set of video lessons.

To reflect some other Spring Framework updates, will make me rework 80% of
the course. It is is very challenging to make video lessons up to date
every time there is a change in a framework. Especially when you have
multiple courses.
